### ISSUE TITLE
Don't require('angular');

### ISSUE THREAD

**Issue by ghost** [Pathgather/popeye#1]
I love the look of the module, looking forward to trying it out.

I'm running into an issue though. I'm including this in a project that's using webpack/commonjs (but not using the angular npm module - since I'm serving angular from a CDN). I've installed this package via bower (so no npm dependencies have been installed), and I'm getting an error when the library code is trying to run _require("angular")_ I'd guess browserify users might face the same issue.

```
  if (typeof require === "function") {
    angular = require("angular");
    popeye(angular);
  } else {
    popeye(window.angular);
  }
```

I've been looking at some other angular modules that are packaged via npm to see how they handle this scenario (popular ones like angular-messages, angular-cookies, ui-bootstrap, etc.) - it seems like they typically just assume to find "angular" on the global (window) object.

Will try to do some testing later and create a PR - let me know if you have any thoughts.

**Comment by NevilleS** [comment]
Hmm, happy to help debug this. I use Browserify to include this...

Maybe if we tested if angular was already on the window, use that? Then fallback to npm? That'd work for me; and might be a best practice...

**Comment by NevilleS** [comment]
That previous comment was basically jibberish, let's try it again!

I've definitely tested using Browserify (the demo page is bundled via Browserify using the npm version of angular). I think what's happening for you is that `require` is defined, but you don't actually want to pull in Angular via `require`, like I do.

I think it's safe to invert the logic here to first try to find Angular on `window`, and then try to `require` it. That would probably work for both of us. I'll create a branch for you to try this...

**Comment by ghost** [comment]
No problem, I'm in the process of drafting the same gibberish! I was thinking the same... in the sense that that's actually what I actually to get it working in the local copy.

I'm looking at some other projects like angular_material and it does do something similar to what you were doing:

``` javascript
// Should already be required, here for clarity
require('angular');

// Load Angular and dependent libs
require('angular-animate');
require('angular-aria');

// Now load Angular Material
require('./angular-material');

// Export namespace
module.exports = 'ngMaterial';
```

but then the more basic modules, which only have dependencies on angular, weren't explicitly doing a require('angular'). I'm not exactly sure what the best practice is, part of this may be a bad webpack config on my part (it's a little unique in the sense that I'm using angular from a CDN, rather than bundling it as a local npm dependency). I can definitely do some testing off of the branch if you don't mind creating it (or I can create one later tonight and prepare a PR).

Thanks!

**Comment by NevilleS** [comment]
Try out the prefer-window-angular branch I just pushed (https://github.com/Pathgather/popeye/blob/prefer-window-angular/release/popeye.js)

**Comment by ghost** [comment]
Excellent - that fixed it. Thanks!

**Comment by NevilleS** [comment]
Cool. It makes sense why this would fail if you aren't actually distributing angular itself with your app. I think this "prefer window.angular" pattern is probably best practice, since the whole "using npm for the frontend" is still pretty new.

I'll spin a new bower build for you too so you can pull this in via regular bower too!

**Comment by NevilleS** [comment]
There you go, it should be available via `bower update` now. Thanks for helping debug :+1:

**Comment by ghost** [comment]
Thanks for taking a look so promptly, nice job!
