### ISSUE TITLE
change parent container [bug]

### ISSUE THREAD

**Issue by karneaud** [Pathgather/popeye#8]
The service works good but when you use ng-view to load/ unload pages and use the back button on the browser when the popup is open the popup remains open even though the page changes. 

Is there a way to change the parent container that the popeye is appended too?

**Comment by NevilleS** [comment]
Even if there was, Popeye manages some global state in the service that would need to be cleaned up nicely. If you want the modal to be dismissed when the route changes, I'd recommend hooking up a global event handle to call `Popeye.closeCurrentModal()` instead.

**Comment by NevilleS** [comment]
Closing this for now - if you feel that solution is inadequate for some reason, let me know, but I'd recommend doing that instead of relying on the DOM structure to manage global state like this 👍
